<?php

namespace GescanPim\Bundle\ConnectorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttributeListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeListRepository extends EntityRepository
{
    
    public function createOrUpdate($sku,$mappingCodeId,$value)
    {
        $attributeList = $this->findOneBy(array('sku'=>$sku,'mappingCodeId'=>$mappingCodeId));
        if (!$attributeList) {
            $attributeList = new AttributeList();
            $attributeList->setSku($sku);
            $attributeList->setMappingCodeId($mappingCodeId);
        }
        $attributeList->setValue($value);
        $this->getEntityManager()->persist($attributeList);
        $this->getEntityManager()->flush($attributeList);
        $this->getEntityManager()->detach($attributeList);
        unset($attributeList);
    }
}
