
DELETE FROM `MappingCode` WHERE `type` = ''color'';
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('gray','eleknet','color','GRAY','grey',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('ivory','eleknet','color','IVORY','ivory',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('black','eleknet','color','BLACK','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('red','eleknet','color','RED','red',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('amber','eleknet','color','AMBER','red',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('ansi/asa 61 gray','eleknet','color','ANSI/ASA 61 GRAY','grey',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('clear','eleknet','color','CLEAR','clear',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('stainless steel','magento','color','Stainless Steel','metal',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('white','eleknet','color','WHITE','white',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('blue','eleknet','color','BLUE','blue',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('yellow','eleknet','color','YELLOW','yellow',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('purple','eleknet','color','PURPLE','purple',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('orange','eleknet','color','ORANGE','orange',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('olive','eleknet','color','OLIVE','green',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('pink','eleknet','color','PINK','pink',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('gold','eleknet','color','GOLD','gold',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('green','eleknet','color','GREEN','green',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('brown','eleknet','color','BROWN','brown',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('red baking enamel','eleknet','color','RED BAKING ENAMEL','red',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('ansi/asa 61 gray body, white panel','eleknet','color','ANSI/ASA 61 GRAY BODY, WHITE PANEL','grey',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('asa 61 gray','eleknet','color','ASA 61 GRAY','grey',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('ral 7032 beige','eleknet','color','RAL 7032 BEIGE','beige',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('satin red','eleknet','color','SATIN RED','red',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('black knob','eleknet','color','BLACK KNOB','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('green top, red bottom','eleknet','color','GREEN TOP, RED BOTTOM','green',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('black top, red bottom','eleknet','color','BLACK TOP, RED BOTTOM','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('black lever','eleknet','color','BLACK LEVER','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('green tracer','eleknet','color','GREEN TRACER','green',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('black, red','eleknet','color','BLACK, RED','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('white inside, ansi/asa 61 gray outside','eleknet','color','WHITE INSIDE, ANSI/ASA 61 GRAY OUTSIDE','grey',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('natural','eleknet','color','NATURAL','none',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('beige','eleknet','color','BEIGE','beige',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('matte black','eleknet','color','MATTE BLACK','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('black, white','eleknet','color','BLACK, WHITE','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('gray front','eleknet','color','GRAY FRONT','grey',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('white','magento','color','White','white',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('ansi 61 gray','eleknet','color','ANSI 61 GRAY','grey',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('tan','eleknet','color','TAN','beige',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('black','magento','color','Black','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('blue/gray','eleknet','color','BLUE/GRAY','blue',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('aluminum plate, white knob','eleknet','color','ALUMINUM PLATE, WHITE KNOB','metal',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('almond','eleknet','color','ALMOND','beige',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('silver','magento','color','Silver','silver',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('light almond','eleknet','color','LIGHT ALMOND','beige',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('stainless steel','eleknet','color','STAINLESS STEEL','metal',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('silver','eleknet','color','SILVER','silver',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('blue','magento','color','Blue','blue',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('yellow','magento','color','Yellow','yellow',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('designer white','eleknet','color','DESIGNER WHITE','white',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('appliance white','eleknet','color','APPLIANCE WHITE','white',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('frost','eleknet','color','FROST',NULL,1);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('opal','eleknet','color','OPAL','white',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('orange peel','eleknet','color','ORANGE PEEL','orange',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('inferno','eleknet','color','INFERNO','orange',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('ice','eleknet','color','ICE','blue',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('glacier','eleknet','color','GLACIER','blue',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('cobalt','eleknet','color','COBALT','blue',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('amber drift','eleknet','color','AMBER DRIFT','red',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('metallic gray','eleknet','color','METALLIC GRAY','metal',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('red','magento','color','Red','red',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('snow','eleknet','color','SNOW','white',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('midnight','eleknet','color','MIDNIGHT','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('eggshell','eleknet','color','EGGSHELL','white',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('biscuit','eleknet','color','BISCUIT',NULL,1);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('limestone','eleknet','color','LIMESTONE','stone',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES(''color'less','eleknet','color','COLORLESS','none',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('clear lid, gray','eleknet','color','CLEAR LID, GRAY','grey',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('yellow face, black shell','eleknet','color','YELLOW FACE, BLACK SHELL','yellow',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('black/white','eleknet','color','BLACK/WHITE','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('black, clear','eleknet','color','BLACK, CLEAR','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('black face, gray flange','eleknet','color','BLACK FACE, GRAY FLANGE','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('black back, white front','eleknet','color','BLACK BACK, WHITE FRONT','black',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('paintable gray','eleknet','color','PAINTABLE GRAY','grey',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('ruby','eleknet','color','RUBY','red',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('green','magento','color','Green','green',0);
INSERT INTO MappingCode(code, source,type,initialValue,value,ignore) VALUES('orange','magento','color','Orange','orange',0);
