/*
-- Query: SELECT *
 FROM akeneo.MappingCode where type = 'manufacturer'
-- Date: 2014-06-19 10:43
*/

DELETE FROM `MappingCode` WHERE `type` = 'manufacturer';
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1720,'A.C.DANDY PRODUCTS LTD.','globale','manufacturer','A.C.DANDY PRODUCTS LTD.','A.C.Dandy Products',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1721,'A&E CONCRETE PRECAST PROD.LTD.','globale','manufacturer','A&E CONCRETE PRECAST PROD.LTD.','A&E Concrete Precast',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1722,'ABB INC.','globale','manufacturer','ABB INC.','ABB',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1723,'AC COMPONENTS INC','globale','manufacturer','AC COMPONENTS INC',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1724,'ACCULITE MFG.INC.','globale','manufacturer','ACCULITE MFG.INC.','Acculite Mfg.',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1725,'ACE MANUFACTURING METALS LTD','globale','manufacturer','ACE MANUFACTURING METALS LTD','Ace Manufacturing Metals',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1726,'ACME STAPLE COMPANY, INC.','globale','manufacturer','ACME STAPLE COMPANY, INC.','Acme Staple',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1727,'ACUITY BRANDS LIGHTING CANADA','globale','manufacturer','ACUITY BRANDS LIGHTING CANADA','Acuity Brands',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1728,'ACURA EMBEDDED SYSTEMS INC.','globale','manufacturer','ACURA EMBEDDED SYSTEMS INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1729,'ADVANCE BATTERY','globale','manufacturer','ADVANCE BATTERY',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1730,'AIMLITE CORP','globale','manufacturer','AIMLITE CORP','Aimlite',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1731,'AIR KING','globale','manufacturer','AIR KING','Air King',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1732,'ALCAN CABLE','globale','manufacturer','ALCAN CABLE','General Cable',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1733,'ALICO INDUSTRIES','globale','manufacturer','ALICO INDUSTRIES','Alico Industries',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1734,'ALL POWER PRODUCTS INC.','globale','manufacturer','ALL POWER PRODUCTS INC.','All Power Products',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1735,'ALLDEC TRADING CO.','globale','manufacturer','ALLDEC TRADING CO.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1736,'ALLIED INNOVATIONS','globale','manufacturer','ALLIED INNOVATIONS','Allied Innovations',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1737,'ALLTEMP PRODUCTS COMPANY LTD','globale','manufacturer','ALLTEMP PRODUCTS COMPANY LTD','Alltemp Products Company',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1738,'AMERICAN ELECTRIC LIGHTING','globale','manufacturer','AMERICAN ELECTRIC LIGHTING','American Electric Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1739,'Amprobe','globale','manufacturer','Amprobe','Fluke',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1740,'ANCHOR PRODUCTS','globale','manufacturer','ANCHOR PRODUCTS','Anchor Products',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1741,'Appleton','globale','manufacturer','Appleton','Emerson Industrial',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1742,'APPLIED POWER CANADA LTD.','globale','manufacturer','APPLIED POWER CANADA LTD.','Applied Power',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1743,'APPLIED SYSTEMS ENGINEERING','globale','manufacturer','APPLIED SYSTEMS ENGINEERING',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1744,'ARGO INTERNATIONAL CORPORATION','globale','manufacturer','ARGO INTERNATIONAL CORPORATION',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1745,'ARLINGTON INDUSTRIES INC.','globale','manufacturer','ARLINGTON INDUSTRIES INC.','Arlington',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1746,'ARROW ELECTRONICS, INC','globale','manufacturer','ARROW ELECTRONICS, INC','Arrow Electronic',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1747,'ARROW FASTENER CANADA, INC','globale','manufacturer','ARROW FASTENER CANADA, INC','Arrow Fastener',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1748,'ASSOCIATED TELEPHONE','globale','manufacturer','ASSOCIATED TELEPHONE',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1749,'ATELIO LIGHTING QUE.','globale','manufacturer','ATELIO LIGHTING QUE.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1750,'ATLAS COPCO CONSTRUCTION &','globale','manufacturer','ATLAS COPCO CONSTRUCTION &',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1751,'B J ELECTRIC SUPPLIES LTD','globale','manufacturer','B J ELECTRIC SUPPLIES LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1752,'B.A ROBINSON CO. LTD','globale','manufacturer','B.A ROBINSON CO. LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1753,'BANVIL 2000','globale','manufacturer','BANVIL 2000','Banvil 2000',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1754,'BATTERYSONIC INC.','globale','manufacturer','BATTERYSONIC INC.','Batterysonic',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1755,'BC ELECTRICAL ASSOCIATION','globale','manufacturer','BC ELECTRICAL ASSOCIATION',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1756,'BEGHELLI INC','globale','manufacturer','BEGHELLI INC','Beghelli',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1757,'BEL PRODUCTS INC.','globale','manufacturer','BEL PRODUCTS INC.','Bel Products',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1758,'BELDON SALES LTD.','globale','manufacturer','BELDON SALES LTD.','Beldon Sales',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1759,'BERLET ELECTRONICS LTD.','globale','manufacturer','BERLET ELECTRONICS LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1760,'BJ TAKE INC','globale','manufacturer','BJ TAKE INC','BJ take',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1761,'BLUE LINE INNOVATIONS INC','globale','manufacturer','BLUE LINE INNOVATIONS INC','Blue Line Innovation',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1762,'BOB DALE GLOVES & IMPORTS LTD.','globale','manufacturer','BOB DALE GLOVES & IMPORTS LTD.','Bob Dale Gloves & Imports',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1763,'BREWS SUPPLY LTD','globale','manufacturer','BREWS SUPPLY LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1764,'Broan','globale','manufacturer','Broan',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1765,'BROAN-NUTONE','globale','manufacturer','BROAN-NUTONE','Broan-Nutone',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1766,'BROCK WHITE CANADA COMPANY','globale','manufacturer','BROCK WHITE CANADA COMPANY','Brock White',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1767,'BRUMALL MFG. CORP. LTD.','globale','manufacturer','BRUMALL MFG. CORP. LTD.','Brumall Manufacturing',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1768,'BURNDY CANADA INC.','globale','manufacturer','BURNDY CANADA INC.','Burndy',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1769,'BURTEK SYSTEMS INC.','globale','manufacturer','BURTEK SYSTEMS INC.','Burtek Systems',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1770,'CALRAD','globale','manufacturer','CALRAD','Calrad',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1771,'CAN-CON INDUSTRIES INC.','globale','manufacturer','CAN-CON INDUSTRIES INC.','Can-Con Industries',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1772,'CANADA HAND DRYERS','globale','manufacturer','CANADA HAND DRYERS','Canada Hand Dryers',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1773,'CANADIAN ELECTRICAL RACEWAYS','globale','manufacturer','CANADIAN ELECTRICAL RACEWAYS','Canadian Electrical Raceways',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1774,'CANARA MOTOR MANAGEMENT','globale','manufacturer','CANARA MOTOR MANAGEMENT','Canara Motor Management',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1775,'CANARM','globale','manufacturer','CANARM','Canarm',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1776,'CARBON BRUSH SUPPLY LTD.','globale','manufacturer','CARBON BRUSH SUPPLY LTD.','Carbon Brush Supply',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1777,'CCI THERMAL','globale','manufacturer','CCI THERMAL',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1778,'CCI THERMAL TECHNOLOGIES INC','globale','manufacturer','CCI THERMAL TECHNOLOGIES INC',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1779,'CCI THERMAL TECHNOLOGIES INC.','globale','manufacturer','CCI THERMAL TECHNOLOGIES INC.','Cci Thermal Technologies',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1780,'CEMENTEX PRODUCTS, INC.','globale','manufacturer','CEMENTEX PRODUCTS, INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1781,'CENTENNIAL WIRE PRODUCTS LTD','globale','manufacturer','CENTENNIAL WIRE PRODUCTS LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1782,'CENTRAL CANADA INDUSTRIES INC','globale','manufacturer','CENTRAL CANADA INDUSTRIES INC',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1783,'CENTURY VALLEN','globale','manufacturer','CENTURY VALLEN',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1784,'CFI','globale','manufacturer','CFI','Philips Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1785,'CHARTWELL AUTOMATION INC.','globale','manufacturer','CHARTWELL AUTOMATION INC.','Chartwell Automation',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1786,'CHATAWAY AGENCIES INC.','globale','manufacturer','CHATAWAY AGENCIES INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1787,'CHEMCO ELECTRICAL CONTR. LTD.','globale','manufacturer','CHEMCO ELECTRICAL CONTR. LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1788,'CHUBB EDWARDS','globale','manufacturer','CHUBB EDWARDS','Chubb Edwards',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1789,'CIMTEC AUTOMATION, LLC','globale','manufacturer','CIMTEC AUTOMATION, LLC','Cimtec Automation, Llc',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1790,'CODE ELECTRIC','globale','manufacturer','CODE ELECTRIC','Code Electric',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1791,'COLOR KINETICS INC.','globale','manufacturer','COLOR KINETICS INC.','Philips Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1792,'COLUMBIA LIGHTING','globale','manufacturer','COLUMBIA LIGHTING','Columbia Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1793,'COLUMBIA-MBF','globale','manufacturer','COLUMBIA-MBF','Columbia MBF',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1794,'COMMANDER ELECTRICAL EQUIPMENT','globale','manufacturer','COMMANDER ELECTRICAL EQUIPMENT',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1795,'COMMERCIAL LIGHTING PROD LTD','globale','manufacturer','COMMERCIAL LIGHTING PROD LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1796,'COMMERCIAL ROLL FORMED PROD LT','globale','manufacturer','COMMERCIAL ROLL FORMED PROD LT','Commercial Roll Form',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1797,'COMPAGNIE 3M CANADA','globale','manufacturer','COMPAGNIE 3M CANADA','3M',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1798,'CONTACT ENVIRONMENTAL INC','globale','manufacturer','CONTACT ENVIRONMENTAL INC','Contact Environmental',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1799,'CONTRAST LIGHTING M.L. INC.','globale','manufacturer','CONTRAST LIGHTING M.L. INC.','Contrast Lighting M.L.',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1800,'CONTROL DESIGN SUPPLY INC.','globale','manufacturer','CONTROL DESIGN SUPPLY INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1801,'COOPER WIRING DEVICES','globale','manufacturer','COOPER WIRING DEVICES','Cooper Wiring Devices',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1802,'COPPERLOGIC  LTD','globale','manufacturer','COPPERLOGIC  LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1803,'CRC CANADA CO.','globale','manufacturer','CRC CANADA CO.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1804,'CROMPTON WESTERN CANADA','globale','manufacturer','CROMPTON WESTERN CANADA',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1805,'CROUSE-HINDS CANADA','globale','manufacturer','CROUSE-HINDS CANADA',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1806,'DAHL BROTHERS CAN LTD.','globale','manufacturer','DAHL BROTHERS CAN LTD.','Dahl Brothers',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1807,'DALS LIGHTING, INC','globale','manufacturer','DALS LIGHTING, INC','Dals Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1808,'DANFOSS INC','globale','manufacturer','DANFOSS INC','DanFoss',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1809,'DASAL INDUSTRIES LTD.','globale','manufacturer','DASAL INDUSTRIES LTD.','Dasal Industries',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1810,'DATA COMM ELECTRONICS INC.','globale','manufacturer','DATA COMM ELECTRONICS INC.','Data Comm Electronics',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1811,'DEALER SOURCE','globale','manufacturer','DEALER SOURCE',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1812,'DECA CABLES INC.','globale','manufacturer','DECA CABLES INC.','Deca Cables',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1813,'DELTA GROUP','globale','manufacturer','DELTA GROUP','Delta Group',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1814,'DICON GLOBAL INC.','globale','manufacturer','DICON GLOBAL INC.','Dicon Global',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1815,'DIMPLEX NORTH AMERICA LIMITED','globale','manufacturer','DIMPLEX NORTH AMERICA LIMITED','Dimplex',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1816,'DISTRI-LITE INC','globale','manufacturer','DISTRI-LITE INC',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1817,'DISTRIBUTION ATIS INC.','globale','manufacturer','DISTRIBUTION ATIS INC.','Distribution Atis',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1818,'DITEK','globale','manufacturer','DITEK','Ditek',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1819,'DIXON ELECTRIC','globale','manufacturer','DIXON ELECTRIC',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1820,'DNA DATA NETWORKING','globale','manufacturer','DNA DATA NETWORKING',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1821,'DOUGLAS LIGHTING CONTROLS','globale','manufacturer','DOUGLAS LIGHTING CONTROLS','Douglas Lighting Controls',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1822,'DUCT-O-WIRE CANADA LTD.','globale','manufacturer','DUCT-O-WIRE CANADA LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1823,'DUNDAS-JAFINE INC.','globale','manufacturer','DUNDAS-JAFINE INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1824,'Duracell','globale','manufacturer','Duracell','Duracell',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1825,'DYSON CANADA LIMITED','globale','manufacturer','DYSON CANADA LIMITED','Dyson',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1826,'E.C.M.','globale','manufacturer','E.C.M.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1827,'E.S. GALLAGHER SALES LTD.','globale','manufacturer','E.S. GALLAGHER SALES LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1828,'EARTHTRONICS','globale','manufacturer','EARTHTRONICS','Earthtronics',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1829,'EASY HEAT LTD','globale','manufacturer','EASY HEAT LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1830,'Eaton','globale','manufacturer','Eaton',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1831,'EATON INDUSTRIES (CANADA)','globale','manufacturer','EATON INDUSTRIES (CANADA)','Eaton',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1832,'ECLAT LIGHTING LTD.','globale','manufacturer','ECLAT LIGHTING LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1833,'ECOTECH HYDRONICS & HEATING','globale','manufacturer','ECOTECH HYDRONICS & HEATING',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1834,'ECS ELECTRICAL CABLE SUPPLY','globale','manufacturer','ECS ELECTRICAL CABLE SUPPLY',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1835,'EDGE ELECTRICAL MARKETING INC.','globale','manufacturer','EDGE ELECTRICAL MARKETING INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1836,'EECOL ELECTRIC CORP.','globale','manufacturer','EECOL ELECTRIC CORP.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1837,'EECOL ELECTRIC LTD.','globale','manufacturer','EECOL ELECTRIC LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1838,'EGS ELECTRICAL GROUP CANADA LT','globale','manufacturer','EGS ELECTRICAL GROUP CANADA LT','Emerson Industrial',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1839,'EIKO CANADA','globale','manufacturer','EIKO CANADA','Eiko',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1840,'ELECTRIC INSULATION','globale','manufacturer','ELECTRIC INSULATION',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1841,'ELECTRO SONIC','globale','manufacturer','ELECTRO SONIC',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1842,'ELECTROTEK LTD','globale','manufacturer','ELECTROTEK LTD','Electrotek',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1843,'ELECTROWIND','globale','manufacturer','ELECTROWIND',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1844,'Elite','globale','manufacturer','Elite',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1845,'ELITE LIGHTING','globale','manufacturer','ELITE LIGHTING','Elite Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1846,'EMERGI-LITE LIMITED','globale','manufacturer','EMERGI-LITE LIMITED','Thomas & Betts',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1847,'EMERSON ELECTRIC CANADA LTD.','globale','manufacturer','EMERSON ELECTRIC CANADA LTD.','Emerson',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1848,'ERICO CANADA INC.','globale','manufacturer','ERICO CANADA INC.','Erico',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1849,'ERIKSON CONSUMER','globale','manufacturer','ERIKSON CONSUMER','Erikson Consumer',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1850,'ETLIN, DANIELS.','globale','manufacturer','ETLIN, DANIELS.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1851,'EXCEL LIGHTING & MFG LTD.','globale','manufacturer','EXCEL LIGHTING & MFG LTD.','Excel Lighting & Manufacturer',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1852,'EXM MANUFACTURING','globale','manufacturer','EXM MANUFACTURING','Exm Manufacturing',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1853,'FACTOR ELECTRONICS','globale','manufacturer','FACTOR ELECTRONICS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1854,'FEDERAL SIGNAL','globale','manufacturer','FEDERAL SIGNAL','Federal Signal',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1855,'FIRESTOP SYSTEMS LTD.','globale','manufacturer','FIRESTOP SYSTEMS LTD.','Firestop Systems',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1856,'Flextherm','globale','manufacturer','Flextherm',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1857,'FLEXTHERM INC','globale','manufacturer','FLEXTHERM INC','Flextherm Inc',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1858,'FLODRAULIC','globale','manufacturer','FLODRAULIC','Flodraulic',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1859,'Fluke','globale','manufacturer','Fluke',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1860,'FLUKE ELECTRONICS CANADA LP','globale','manufacturer','FLUKE ELECTRONICS CANADA LP','Fluke',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1861,'FRASER VALLEY STEEL & WIRE LTD','globale','manufacturer','FRASER VALLEY STEEL & WIRE LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1862,'FRE COMPOSITES (2005) , INC','globale','manufacturer','FRE COMPOSITES (2005) , INC','FRE Composite',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1863,'FURNAS ELECTRIC COMPANY','globale','manufacturer','FURNAS ELECTRIC COMPANY','Siemens',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1864,'FUSETEK','globale','manufacturer','FUSETEK','Fusetek',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1865,'G.A.F. SALES','globale','manufacturer','G.A.F. SALES',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1866,'G.S. BATTERY CANADA','globale','manufacturer','G.S. BATTERY CANADA','GS Battery',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1867,'GE CANADA','globale','manufacturer','GE CANADA','Ge Canada',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1868,'GE CANADA  USD','globale','manufacturer','GE CANADA  USD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1869,'GE DRIVES','globale','manufacturer','GE DRIVES',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1870,'GE ENERGY & MOTORS CANADA','globale','manufacturer','GE ENERGY & MOTORS CANADA',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1871,'GE INTELLIGENT PLATFORMS','globale','manufacturer','GE INTELLIGENT PLATFORMS','Ge Intelligent Platforms',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1872,'GE MULTILIN','globale','manufacturer','GE MULTILIN','Ge Multilin',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1873,'GE TRANSFORMERS','globale','manufacturer','GE TRANSFORMERS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1874,'Generac','globale','manufacturer','Generac',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1875,'GENERAC POWER SYSTEMS','globale','manufacturer','GENERAC POWER SYSTEMS','Generac Power Systems',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1876,'GENERAL CABLE','globale','manufacturer','GENERAL CABLE',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1877,'GENERAL CABLE COMPANY, LTD','globale','manufacturer','GENERAL CABLE COMPANY, LTD','General Cable',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1878,'GENERAL ELECTRIC CANADA','globale','manufacturer','GENERAL ELECTRIC CANADA','General Electric',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1879,'GENERIC CONDUIT','globale','manufacturer','GENERIC CONDUIT',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1880,'GENERIC CONDUIT FITTINGS','globale','manufacturer','GENERIC CONDUIT FITTINGS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1881,'GEORGE M. FRASER LTD','globale','manufacturer','GEORGE M. FRASER LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1882,'GERRIE ELECTRIC','globale','manufacturer','GERRIE ELECTRIC',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1883,'GESCAN CLAIM REBATE','globale','manufacturer','GESCAN CLAIM REBATE',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1884,'GESCAN GENERIC TOOLS/SUPPLIES','globale','manufacturer','GESCAN GENERIC TOOLS/SUPPLIES',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1885,'GEXPRO','globale','manufacturer','GEXPRO',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1886,'GIANTECH PLASTIC PRODUCTS','globale','manufacturer','GIANTECH PLASTIC PRODUCTS','Giantech Plastic Products',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1887,'GM Lighting','globale','manufacturer','GM Lighting','GM Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1888,'GM LIGHTING LLC','globale','manufacturer','GM LIGHTING LLC','GM Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1889,'GRAFTON WEST','globale','manufacturer','GRAFTON WEST',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1890,'GRANTA MANUFACTURING INC (GMI)','globale','manufacturer','GRANTA MANUFACTURING INC (GMI)',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1891,'Greenlee','globale','manufacturer','Greenlee',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1892,'GREENLEE TEXTRON','globale','manufacturer','GREENLEE TEXTRON','Greenlee Textron',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1893,'GREYSTONE ENERGY SYSTEMS INC.','globale','manufacturer','GREYSTONE ENERGY SYSTEMS INC.','Greystone Energy Systems',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1894,'GUILLEVIN INTERNATIONAL CO','globale','manufacturer','GUILLEVIN INTERNATIONAL CO',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1895,'GVA LIGHTING','globale','manufacturer','GVA LIGHTING','Gva Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1896,'HAMMOND MANUFACTURING CO. LTD','globale','manufacturer','HAMMOND MANUFACTURING CO. LTD','Hammond Manufacturing',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1897,'HAMMOND POWER SOLUTIONS INC','globale','manufacturer','HAMMOND POWER SOLUTIONS INC','Hammond Power Solutions',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1898,'HASKEL LAMPS','globale','manufacturer','HASKEL LAMPS','Haskel Lamps',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1899,'HCS HEATER CONTROLS & SENSORS','globale','manufacturer','HCS HEATER CONTROLS & SENSORS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1900,'HEATHCO CANADA','globale','manufacturer','HEATHCO CANADA','HeathCo',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1901,'HELLERMANNTYTON CANADA INC.','globale','manufacturer','HELLERMANNTYTON CANADA INC.','Hellermann Tyton',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1902,'HILTI(CANADA) CORPORATION','globale','manufacturer','HILTI(CANADA) CORPORATION','Hilti',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1903,'HOFFMAN ENCLOSURES CO CANADA','globale','manufacturer','HOFFMAN ENCLOSURES CO CANADA','Hoffman Enclosures',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1904,'HOLLAND IMPORTS INC.','globale','manufacturer','HOLLAND IMPORTS INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1905,'HONEYWELL INDUSTRIAL','globale','manufacturer','HONEYWELL INDUSTRIAL','Honeywell Industrial',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1906,'HONEYWELL SENSING AND CONTROL','globale','manufacturer','HONEYWELL SENSING AND CONTROL','Honeywell Sensing And Control',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1907,'HORNER APG LLC','globale','manufacturer','HORNER APG LLC','Honer APG',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1908,'HOUSE OF ELECTRICAL','globale','manufacturer','HOUSE OF ELECTRICAL',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1909,'HOYME MANUFACTURING INC.','globale','manufacturer','HOYME MANUFACTURING INC.','Hoyme Manufacturing',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1910,'Hubbell','globale','manufacturer','Hubbell',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1911,'HUBBELL CANADA INC.','globale','manufacturer','HUBBELL CANADA INC.','Hubbell',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1912,'HUBBELL LIGHTING','globale','manufacturer','HUBBELL LIGHTING','Hubbell',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1913,'HYDEL ENTERPRISES INC.','globale','manufacturer','HYDEL ENTERPRISES INC.','Hydel Enterprises',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1914,'I-GUARD CORPORATION','globale','manufacturer','I-GUARD CORPORATION','I Guard',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1915,'Ideal','globale','manufacturer','Ideal',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1916,'IDEAL INDUSTRIES (CANADA),CORP','globale','manufacturer','IDEAL INDUSTRIES (CANADA),CORP','Ideal Industries',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1917,'IDEC CANADA LTD','globale','manufacturer','IDEC CANADA LTD','Idec',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1918,'IDOCX','globale','manufacturer','IDOCX','Idocx',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1919,'ILSCO OF CANADA LTD','globale','manufacturer','ILSCO OF CANADA LTD','Ilsco',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1920,'INDUSTRIAL INSTRUMENT SERVICES','globale','manufacturer','INDUSTRIAL INSTRUMENT SERVICES',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1921,'INFORESIGHT CONSUMER PRODUCTS','globale','manufacturer','INFORESIGHT CONSUMER PRODUCTS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1922,'INFRATECH','globale','manufacturer','INFRATECH','Infratech',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1923,'INTERMATIC INC.','globale','manufacturer','INTERMATIC INC.','Intermatic',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1924,'INVENSYS CLIMATE CONTROLS','globale','manufacturer','INVENSYS CLIMATE CONTROLS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1925,'INVENSYS SYSTEMS CANADA INC','globale','manufacturer','INVENSYS SYSTEMS CANADA INC','Invensys',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1926,'Ipex','globale','manufacturer','Ipex',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1927,'IPEX ELECTRICAL INC.','globale','manufacturer','IPEX ELECTRICAL INC.','Ipex Electrical',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1928,'ISTED TECHNICAL SALES','globale','manufacturer','ISTED TECHNICAL SALES',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1929,'ITRON CANADA, INC','globale','manufacturer','ITRON CANADA, INC','Itron',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1930,'J.R. STEPHENSON LTD.','globale','manufacturer','J.R. STEPHENSON LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1931,'JACKSON POWER & ELECTRIC LTD.','globale','manufacturer','JACKSON POWER & ELECTRIC LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1932,'JAFTECH MANUFACTURING LTD.','globale','manufacturer','JAFTECH MANUFACTURING LTD.','Jaftech Manufacturing',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1933,'JEFFERS ENTERPRISES','globale','manufacturer','JEFFERS ENTERPRISES',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1934,'Juno','globale','manufacturer','Juno',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1935,'JUNO LIGHTING LTD.','globale','manufacturer','JUNO LIGHTING LTD.','Juno Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1936,'KEENE-WIDELITE','globale','manufacturer','KEENE-WIDELITE','Philips Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1937,'KEL TEK','globale','manufacturer','KEL TEK',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1938,'KENDAL LIGHTING (B.C.) INC.','globale','manufacturer','KENDAL LIGHTING (B.C.) INC.','Kendal Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1939,'KICHLER','globale','manufacturer','KICHLER','Kichler',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1940,'Kidde','globale','manufacturer','Kidde',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1941,'KIDDE CANADA INC.','globale','manufacturer','KIDDE CANADA INC.','Kidde Canada',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1942,'KIM LIGHTING INC.','globale','manufacturer','KIM LIGHTING INC.','Kim Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1943,'KING ELECTRICAL MFG COMPANY','globale','manufacturer','KING ELECTRICAL MFG COMPANY','King Electric',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1944,'KINGSWAY INSTRUMENTS INC.','globale','manufacturer','KINGSWAY INSTRUMENTS INC.','Kingsway Instruments',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1945,'Klein','globale','manufacturer','Klein',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1946,'KLEIN TOOLS','globale','manufacturer','KLEIN TOOLS','Klein Tools',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1947,'KOHLER COMPANY','globale','manufacturer','KOHLER COMPANY','Kohler Company',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1948,'KUNY\'S LEATHER MFG CO LTD.','globale','manufacturer','KUNY\'S LEATHER MFG CO LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1949,'LANCE BISSETT LIMITED','globale','manufacturer','LANCE BISSETT LIMITED','Lance Bissett Limited',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1950,'LEAVENS AVIATION INC.','globale','manufacturer','LEAVENS AVIATION INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1951,'LEDTRONICS INC','globale','manufacturer','LEDTRONICS INC','Ledtronics Inc',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1952,'LEE INDUSTRIAL','globale','manufacturer','LEE INDUSTRIAL',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1953,'Legrand','globale','manufacturer','Legrand','Legrand',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1954,'LES ECLAIRAGES LINOGENE INC.','globale','manufacturer','LES ECLAIRAGES LINOGENE INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1955,'LEVITON MANUFACTURING OF','globale','manufacturer','LEVITON MANUFACTURING OF','Leviton',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1956,'LIGHTBULB WAREHOUSE','globale','manufacturer','LIGHTBULB WAREHOUSE',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1957,'LIGHTING CONTROL & DESIGN','globale','manufacturer','LIGHTING CONTROL & DESIGN',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1958,'LIGHTOLIER','globale','manufacturer','LIGHTOLIER','Philips Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1959,'LightSpeaker','globale','manufacturer','LightSpeaker','Lightspeaker',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1960,'LIND EQUIPMENT LTD.','globale','manufacturer','LIND EQUIPMENT LTD.','Lind Equipment',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1961,'LINEMASTER','globale','manufacturer','LINEMASTER','Linemaster',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1962,'LITE-SCAPE.COM','globale','manufacturer','LITE-SCAPE.COM','Lite-scape',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1963,'LITELINE CORPORATION','globale','manufacturer','LITELINE CORPORATION','Litelineoration',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1964,'Lithonia','globale','manufacturer','Lithonia','Acuity Brands',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1965,'Logitech','globale','manufacturer','Logitech','Logitech',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1966,'LORD ELECTRICAL INDUSTRIAL','globale','manufacturer','LORD ELECTRICAL INDUSTRIAL',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1967,'Lutron','globale','manufacturer','Lutron',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1968,'LUTRON ELECTRONICS CO. INC.','globale','manufacturer','LUTRON ELECTRONICS CO. INC.','Lutron Electronics',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1969,'MAC PRODUCTS, INC','globale','manufacturer','MAC PRODUCTS, INC','Mac Products',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1970,'MARCUS TRANSFORMER','globale','manufacturer','MARCUS TRANSFORMER','Marcus Transformer',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1971,'MARLEY ENGINEERED PRODUCTS LLC','globale','manufacturer','MARLEY ENGINEERED PRODUCTS LLC','Marley Engineered Products',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1972,'MARTECH','globale','manufacturer','MARTECH','Martech',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1973,'MCM ROPE','globale','manufacturer','MCM ROPE','Mcm Rope',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1974,'MEGAPRO','globale','manufacturer','MEGAPRO','Megapro',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1975,'MERCURY LIGHTING LTD.','globale','manufacturer','MERCURY LIGHTING LTD.','Mercury Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1976,'MERSEN CANADA TORONTO INC','globale','manufacturer','MERSEN CANADA TORONTO INC','Gould Fuses',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1977,'MGE UPS SYSTEMS, INC.','globale','manufacturer','MGE UPS SYSTEMS, INC.','Mge Ups Systems',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1978,'MGM ELECTRIC LTD','globale','manufacturer','MGM ELECTRIC LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1979,'MIDWEST ELECTRIC PRODUCTS INC.','globale','manufacturer','MIDWEST ELECTRIC PRODUCTS INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1980,'MIL-STED DATA PRODUCTS LTD','globale','manufacturer','MIL-STED DATA PRODUCTS LTD','Mil-Sted Data Products',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1981,'Milwaukee','globale','manufacturer','Milwaukee',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1982,'MILWAUKEE ELECTRIC TOOLS','globale','manufacturer','MILWAUKEE ELECTRIC TOOLS','Milwaukee Electric Tools',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1983,'MINERALLAC COMPANY','globale','manufacturer','MINERALLAC COMPANY','Minerallac Company',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1984,'MINUTEMAN POWER TECHNOLOGIES','globale','manufacturer','MINUTEMAN POWER TECHNOLOGIES','Minuteman Power Technologies',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1985,'MIRCOM TECHNOLOGIES LTD.','globale','manufacturer','MIRCOM TECHNOLOGIES LTD.','Mircom Technologies',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1986,'Misc. vendor','globale','manufacturer','Misc. vendor',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1987,'MISCELLANEOUS SUPPLIER','globale','manufacturer','MISCELLANEOUS SUPPLIER',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1988,'MISCELLANEOUS VENDOR','globale','manufacturer','MISCELLANEOUS VENDOR',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1989,'MM PLASTIC(MFG) CO. INC','globale','manufacturer','MM PLASTIC(MFG) CO. INC','MM Plastics',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1990,'MNP LTD','globale','manufacturer','MNP LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1991,'MOLEX CANADA LTD','globale','manufacturer','MOLEX CANADA LTD','Molex',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1992,'MP LIGHTING','globale','manufacturer','MP LIGHTING','Mp Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1993,'NATIONAL CABLE SPECIALIST INC','globale','manufacturer','NATIONAL CABLE SPECIALIST INC',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1994,'NATIONAL ELECTRIC SUPPLY LTD','globale','manufacturer','NATIONAL ELECTRIC SUPPLY LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1995,'NELSON HEAT TRACE','globale','manufacturer','NELSON HEAT TRACE',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1996,'NESCO NATIONAL ELECTRICAL','globale','manufacturer','NESCO NATIONAL ELECTRICAL','Nesco National Electrical',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1997,'NEW MOON LIGHTING AND DESIGN','globale','manufacturer','NEW MOON LIGHTING AND DESIGN',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1998,'NEXANS CANADA INC.','globale','manufacturer','NEXANS CANADA INC.','Nexans',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (1999,'NORTH SAFETY PRODUCTS LTD','globale','manufacturer','NORTH SAFETY PRODUCTS LTD','North Safety Products',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2000,'NORTHERN CABLES','globale','manufacturer','NORTHERN CABLES','Northern Cables',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2001,'NORTHWEST STOVES LTD.','globale','manufacturer','NORTHWEST STOVES LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2002,'NOTIFIER CANADA','globale','manufacturer','NOTIFIER CANADA','Honeywell',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2003,'NSI INDUSTRIES, LLC','globale','manufacturer','NSI INDUSTRIES, LLC',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2004,'Nuheat','globale','manufacturer','Nuheat',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2005,'NUHEAT INDUSTRIES LIMITED','globale','manufacturer','NUHEAT INDUSTRIES LIMITED','Nuheat',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2006,'ON-Q','globale','manufacturer','ON-Q','Legrand',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2007,'ONTOR LIMITED','globale','manufacturer','ONTOR LIMITED','Ontor Limited',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2008,'ORIGAUDIO','globale','manufacturer','ORIGAUDIO',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2009,'ORTRONICS','globale','manufacturer','ORTRONICS','Legrand',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2010,'OSRAM','globale','manufacturer','OSRAM',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2011,'P T I CABLES','globale','manufacturer','P T I CABLES','PTI Cables',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2012,'PAISLEY PRODUCTS OF CANADA INC','globale','manufacturer','PAISLEY PRODUCTS OF CANADA INC','Paisley',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2013,'Panasonic','globale','manufacturer','Panasonic',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2014,'PANASONIC CANADA INC.','globale','manufacturer','PANASONIC CANADA INC.','Panasonic',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2015,'PASS & SEYMOUR','globale','manufacturer','PASS & SEYMOUR','Legrand',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2016,'PAULUHN INC','globale','manufacturer','PAULUHN INC','Pauluhn',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2017,'PEERLESS ELECTRIC','globale','manufacturer','PEERLESS ELECTRIC','Peerless Electric',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2018,'PELICAN CANADA ULC','globale','manufacturer','PELICAN CANADA ULC','Pelican',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2019,'PENTAIR THERMAL MANAGEMENT','globale','manufacturer','PENTAIR THERMAL MANAGEMENT','Pentair Thermal',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2020,'PEPPERL & FUCHS','globale','manufacturer','PEPPERL & FUCHS','Pepperl & Fuchs',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2021,'Philips','globale','manufacturer','Philips',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2022,'PHILIPS LIGHTING','globale','manufacturer','PHILIPS LIGHTING','Philips Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2023,'PNA GROUP INC','globale','manufacturer','PNA GROUP INC','PNA Group',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2024,'POLAR BATTERY LTD.','globale','manufacturer','POLAR BATTERY LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2025,'POLYCAST INTERNATIONAL','globale','manufacturer','POLYCAST INTERNATIONAL',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2026,'PRECISION MULTIPLE CONTROLS','globale','manufacturer','PRECISION MULTIPLE CONTROLS','Precision Multiple Controls',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2027,'PRECOR CONSUMER ELECTRONIC','globale','manufacturer','PRECOR CONSUMER ELECTRONIC','Lightspeaker',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2028,'PREMIER LIGHTING LTD.','globale','manufacturer','PREMIER LIGHTING LTD.','Premier Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2029,'PRESCOLITE','globale','manufacturer','PRESCOLITE','Hubbell',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2030,'PRIME SOURCE BUILDING PRODUCTS','globale','manufacturer','PRIME SOURCE BUILDING PRODUCTS','Lilly Fasteners',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2031,'PRIME WIRE & CABLE','globale','manufacturer','PRIME WIRE & CABLE',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2032,'PRIMEX MANUFACTURING LTD.','globale','manufacturer','PRIMEX MANUFACTURING LTD.','Primex',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2033,'PROCESS FLOW SYSTEMS LTD','globale','manufacturer','PROCESS FLOW SYSTEMS LTD','Process Flow Systems',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2034,'PROCTOR & GAMBLE','globale','manufacturer','PROCTOR & GAMBLE','Duracell',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2035,'PROGRESS LIGHTING-US','globale','manufacturer','PROGRESS LIGHTING-US','Progress Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2036,'PROGRESSIVE SALES CANADA','globale','manufacturer','PROGRESSIVE SALES CANADA',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2037,'PROMO POUCH','globale','manufacturer','PROMO POUCH','Promo Pouch',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2038,'PTI Cables','globale','manufacturer','PTI Cables','PTI Cables',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2039,'PULS, L.P.','globale','manufacturer','PULS, L.P.','Puls',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2040,'PULSAR(VMD) INC.','globale','manufacturer','PULSAR(VMD) INC.','Pulsar',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2041,'QMC METERING SOLUTIONS','globale','manufacturer','QMC METERING SOLUTIONS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2042,'QUADLOGIC METERS CANADA INC.','globale','manufacturer','QUADLOGIC METERS CANADA INC.','Quadlogic Meters',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2043,'R C LIGHTING','globale','manufacturer','R C LIGHTING','RC Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2044,'RAB Design','globale','manufacturer','RAB Design',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2045,'RAB DESIGN LIGHTING INC','globale','manufacturer','RAB DESIGN LIGHTING INC','RAB Design Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2046,'Rack-A-Tiers','globale','manufacturer','Rack-A-Tiers',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2047,'RACK-A-TIERS MFG. INC.','globale','manufacturer','RACK-A-TIERS MFG. INC.','Rack-A-Tiers',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2048,'RAYOVAC CANADA INC. B9155','globale','manufacturer','RAYOVAC CANADA INC. B9155',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2049,'RC Lighting','globale','manufacturer','RC Lighting','RC Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2050,'REGAL CONTROLS LTD','globale','manufacturer','REGAL CONTROLS LTD','Regal Controls',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2051,'REGINA BATTERY DEPOT','globale','manufacturer','REGINA BATTERY DEPOT',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2052,'Remee','globale','manufacturer','Remee',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2053,'REMEE PRODUCTS CORP.','globale','manufacturer','REMEE PRODUCTS CORP.','Remee',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2054,'REX MANUFACTURING','globale','manufacturer','REX MANUFACTURING','Rex Manufacturing',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2055,'RICHARD MCDONALD & ASSOC LTD.','globale','manufacturer','RICHARD MCDONALD & ASSOC LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2056,'RICHARDSON LIGHTING','globale','manufacturer','RICHARDSON LIGHTING',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2057,'RIZE ENTERPRISES','globale','manufacturer','RIZE ENTERPRISES','Rize Enterprises',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2058,'ROBERTSON INC.','globale','manufacturer','ROBERTSON INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2059,'ROTEX MANUFACTURING AND DIST.','globale','manufacturer','ROTEX MANUFACTURING AND DIST.','Rotex Manufacturing And Dist.',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2060,'ROXTEC INC.','globale','manufacturer','ROXTEC INC.','Roxtec',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2061,'RT AGENCIES INC','globale','manufacturer','RT AGENCIES INC','Rt Agencies Inc',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2062,'RUSSELL INDUSTRIES LTD','globale','manufacturer','RUSSELL INDUSTRIES LTD','Russel',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2063,'RUSSOUND','globale','manufacturer','RUSSOUND','Russound',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2064,'SABIC POLYMERSHAPES','globale','manufacturer','SABIC POLYMERSHAPES','Sabic Polymershapes',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2065,'SASCO TUBES & ROLL FORMING INC','globale','manufacturer','SASCO TUBES & ROLL FORMING INC','Sasco Tubes & Roll Forming Inc',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2066,'SASKBATTERY DISTRIBUTORS','globale','manufacturer','SASKBATTERY DISTRIBUTORS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2067,'SAUNA CRAFT','globale','manufacturer','SAUNA CRAFT',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2068,'SENSORSWITCH','globale','manufacturer','SENSORSWITCH','Acuity Brands',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2069,'SERGE BARIL & ASSOCIATES INC.','globale','manufacturer','SERGE BARIL & ASSOCIATES INC.','Serge Baril & Associates',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2070,'SHELLEY INDUSTRIAL AUTOMATION','globale','manufacturer','SHELLEY INDUSTRIAL AUTOMATION',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2071,'SHEPHERD INSTRUMENTS &','globale','manufacturer','SHEPHERD INSTRUMENTS &','Shepherd Instruments & Controls',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2072,'SICK LTD c/o TH1266','globale','manufacturer','SICK LTD c/o TH1266','Sick Optics',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2073,'Siemens','globale','manufacturer','Siemens',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2074,'SIEMENS CANADA LIMITED','globale','manufacturer','SIEMENS CANADA LIMITED','Siemens',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2075,'SIEMENS CONTROL','globale','manufacturer','SIEMENS CONTROL','Siemens',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2076,'SMART BOX CANADA','globale','manufacturer','SMART BOX CANADA','Smart Box Canada',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2077,'SODISCO HOWDEN GROUP INC','globale','manufacturer','SODISCO HOWDEN GROUP INC','Sodisco-Howden',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2078,'SOLA LIGHTING & POWER','globale','manufacturer','SOLA LIGHTING & POWER','Sola Lighting & Power',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2079,'SOUTHWIRE','globale','manufacturer','SOUTHWIRE','Southwire',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2080,'SPARTAN CONTROLS LTD.','globale','manufacturer','SPARTAN CONTROLS LTD.','Spartan Controls',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2081,'STANDARD PRODUCTS INC.','globale','manufacturer','STANDARD PRODUCTS INC.','Standard Products',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2082,'STANLEY TOOLS','globale','manufacturer','STANLEY TOOLS','Stanley Tools',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2083,'STANPRO LIGHTING SYSTEMS INC','globale','manufacturer','STANPRO LIGHTING SYSTEMS INC','Stanpro Lighting Systems',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2084,'STEINEL','globale','manufacturer','STEINEL','Steinel',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2085,'Stelpro','globale','manufacturer','Stelpro',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2086,'STELPRO DESIGN INC.','globale','manufacturer','STELPRO DESIGN INC.','Stelpro Design',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2087,'STERLING VALVE AUTOMATION','globale','manufacturer','STERLING VALVE AUTOMATION','Sterling Valve Automation',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2088,'STUMM ELECTRIC LTD','globale','manufacturer','STUMM ELECTRIC LTD','Stumm Electric',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2089,'STURDY LADDER INC.','globale','manufacturer','STURDY LADDER INC.','Sturdy Ladder',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2090,'STURGEON BAY METAL PRODUCTS','globale','manufacturer','STURGEON BAY METAL PRODUCTS','Sturgeon Bay Metal Products',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2091,'SUMMIT ELECTRIC PRODUCTS','globale','manufacturer','SUMMIT ELECTRIC PRODUCTS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2092,'SUMMIT ELECTRIC PRODUCTS LTD','globale','manufacturer','SUMMIT ELECTRIC PRODUCTS LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2093,'SUPERIOR FLEXIBLE CONDUITS INC','globale','manufacturer','SUPERIOR FLEXIBLE CONDUITS INC','Superior Flex',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2094,'SWIFT DEVICES LTD','globale','manufacturer','SWIFT DEVICES LTD','Swift Devices',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2095,'SWS STAR WARNING SYSTEMS INC.','globale','manufacturer','SWS STAR WARNING SYSTEMS INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2096,'TECH LIGHTING','globale','manufacturer','TECH LIGHTING','Tech Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2097,'TECHNICAL CONSUMER PRODUCTS','globale','manufacturer','TECHNICAL CONSUMER PRODUCTS','TCP',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2098,'TECHSPAN INDUSTRIES INC.','globale','manufacturer','TECHSPAN INDUSTRIES INC.','Techspan Industries',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2099,'TECO-WESTINGHOUSE MOTOR CO','globale','manufacturer','TECO-WESTINGHOUSE MOTOR CO',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2100,'TEVELEC WEST','globale','manufacturer','TEVELEC WEST','Tevelec West',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2101,'TEXCAN, DIV OF SONEPAR DIST.','globale','manufacturer','TEXCAN, DIV OF SONEPAR DIST.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2102,'TG MARKETING','globale','manufacturer','TG MARKETING',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2103,'THE DESIGNERS EDGE, INC.','globale','manufacturer','THE DESIGNERS EDGE, INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2104,'THE WATT STOPPER, INC.','globale','manufacturer','THE WATT STOPPER, INC.','Legrand',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2105,'THOMAS & BETTS','globale','manufacturer','THOMAS & BETTS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2106,'THOMAS & BETTS LTD','globale','manufacturer','THOMAS & BETTS LTD','Thomas & Betts',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2107,'THORN LIGHTING','globale','manufacturer','THORN LIGHTING','Thorn Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2108,'TIMELINE HOLDINGS LTD','globale','manufacturer','TIMELINE HOLDINGS LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2109,'TRADEX SUPPLY LTD.','globale','manufacturer','TRADEX SUPPLY LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2110,'TRANS CANADA WIRE & CABLE CO.','globale','manufacturer','TRANS CANADA WIRE & CABLE CO.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2111,'TRANS WEST SUPPLY COMPANY','globale','manufacturer','TRANS WEST SUPPLY COMPANY',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2112,'TRANSFAB MAGNETIC SOLUTIONS','globale','manufacturer','TRANSFAB MAGNETIC SOLUTIONS','Transfab Magnetic Solutions',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2113,'TRI PYRAMID','globale','manufacturer','TRI PYRAMID','Tri Pyramid',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2114,'TROY FIRE & LIFE SAFETY LTD.','globale','manufacturer','TROY FIRE & LIFE SAFETY LTD.','Troy Fire & Life Safety',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2115,'TRYDOR INDUSTRIES(CANADA) LTD.','globale','manufacturer','TRYDOR INDUSTRIES(CANADA) LTD.','Trydor Industries',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2116,'TSP MARKETING','globale','manufacturer','TSP MARKETING','Tsp Marketing',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2117,'TURNER - COOPER TOOLS','globale','manufacturer','TURNER - COOPER TOOLS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2118,'TURNER & SEYMOUR OF CDA.LTD.','globale','manufacturer','TURNER & SEYMOUR OF CDA.LTD.','Turner & Seymour',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2119,'TYCO ELECTRONICS OF CANADA','globale','manufacturer','TYCO ELECTRONICS OF CANADA','Tyco Electronics',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2120,'U-2, INC.','globale','manufacturer','U-2, INC.','Posh Speakers',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2121,'UBS INDUSTRIES','globale','manufacturer','UBS INDUSTRIES',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2122,'UEI CANADA','globale','manufacturer','UEI CANADA',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2123,'UK PRODUCTS CANADA INC.','globale','manufacturer','UK PRODUCTS CANADA INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2124,'UNISTRUT CANADA LTD.','globale','manufacturer','UNISTRUT CANADA LTD.','Columbia MBF',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2125,'UNIVERSAL LIGHTING TECHNOLOGIE','globale','manufacturer','UNIVERSAL LIGHTING TECHNOLOGIE',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2126,'USHIO AMERICAN INC.','globale','manufacturer','USHIO AMERICAN INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2127,'VANTERA INCORPORATED','globale','manufacturer','VANTERA INCORPORATED','Vantera Incorporated',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2128,'VISCOR INC','globale','manufacturer','VISCOR INC',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2129,'VISION CANADA LTD','globale','manufacturer','VISION CANADA LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2130,'VISIONEERED LIGHTING MFG LTD.','globale','manufacturer','VISIONEERED LIGHTING MFG LTD.','Visioneered Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2131,'VYNCKIER','globale','manufacturer','VYNCKIER',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2132,'W H BRADY INC.','globale','manufacturer','W H BRADY INC.','Brady',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2133,'W INTERCONNECTIONS CANADA INC','globale','manufacturer','W INTERCONNECTIONS CANADA INC','Weidmuller',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2134,'WAGO CORPORATION','globale','manufacturer','WAGO CORPORATION','Wago',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2135,'WattStopper','globale','manufacturer','WattStopper','Legrand',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2136,'WEBER SUPPLY COMPANY INC.','globale','manufacturer','WEBER SUPPLY COMPANY INC.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2137,'WERA TOOLS  LLC','globale','manufacturer','WERA TOOLS  LLC','Wera Tools',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2138,'WEST COAST ELECTRIC LTD.','globale','manufacturer','WEST COAST ELECTRIC LTD.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2139,'WESTWAY ELECTRICAL SUPPLIES','globale','manufacturer','WESTWAY ELECTRICAL SUPPLIES',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2140,'WIDE LOYAL DEVELOPMENT LTD','globale','manufacturer','WIDE LOYAL DEVELOPMENT LTD',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2141,'WIELAND ELECTRIC INC.','globale','manufacturer','WIELAND ELECTRIC INC.','Wieland Electric',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2142,'WIND TRONICS','globale','manufacturer','WIND TRONICS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2143,'WIRE XPRESS c/o SYMCOR INC','globale','manufacturer','WIRE XPRESS c/o SYMCOR INC',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2144,'WIREMOLD','globale','manufacturer','WIREMOLD','Legrand',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2145,'WOODHEAD CANADA LTD','globale','manufacturer','WOODHEAD CANADA LTD','Woodhead Canada',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2146,'WOODS IND.(CANADA) INC.','globale','manufacturer','WOODS IND.(CANADA) INC.','Woods Industries',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2147,'YAMATAKE SENSING CONTROL LTD.','globale','manufacturer','YAMATAKE SENSING CONTROL LTD.','Yamatake Sensing Control',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2230,'woodhead canada','pim','manufacturer','Woodhead Canada','Woodhead Canada',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2231,'burndy / fci','pim','manufacturer','Burndy / FCI','Burndy',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2232,'arlington industries,','pim','manufacturer','Arlington Industries,','Arlington',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2233,'erico canada','pim','manufacturer','Erico Canada','Erico',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2234,'chubb security systems','pim','manufacturer','Chubb Security Systems','Chubb Edwards',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2235,'cooper industries (electrical)','pim','manufacturer','Cooper Industries (Electrical)',NULL,NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2236,'bel products  / produits bel','pim','manufacturer','Bel products  / Produits Bel','Bel Products',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2240,'broan-nutone canada','pim','manufacturer','Broan-Nutone Canada','Broan-Nutone',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2241,'brady','pim','manufacturer','Brady','Brady',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2252,'rab design lighting','pim','manufacturer','Rab Design Lighting','RAB Design Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2254,'siemens canada','pim','manufacturer','Siemens Canada','Siemens',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2256,'mersen canada','pim','manufacturer','Mersen Canada','Gould Fuses',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2257,'juno lighting','pim','manufacturer','Juno Lighting','Juno Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2258,'intermatic','pim','manufacturer','Intermatic','Intermatic',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2259,'hammond manufacturing','pim','manufacturer','Hammond Manufacturing','Hammond Manufacturing',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2273,'hammond power solution','pim','manufacturer','Hammond Power solution','Hammond Power Solutions',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2274,'hubbell canada','pim','manufacturer','Hubbell Canada','Hubbell',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2279,'ideal industries (canada)','pim','manufacturer','Ideal Industries (Canada)','Ideal Industries',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2282,'ilsco of canada','pim','manufacturer','Ilsco of Canada','Ilsco',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2287,'legrand canada','pim','manufacturer','Legrand Canada','Legrand',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2288,'lutron electronics','pim','manufacturer','Lutron Electronics','Lutron Electronics',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2306,'canlyte','pim','manufacturer','Canlyte',NULL,NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2312,'3m canada company','pim','manufacturer','3M Canada Company','3M',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2314,'coleman cable','pim','manufacturer','Coleman Cable',NULL,NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2322,'rack-a-tiers manufacturing','pim','manufacturer','Rack-A-Tiers Manufacturing','Rack-A-Tiers',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2324,'stelpro design','pim','manufacturer','Stelpro Design','Stelpro Design',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2325,'stanley canada','pim','manufacturer','Stanley Canada','Stanley Tools',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2326,'eclairage contraste / contrast lighting','pim','manufacturer','Eclairage Contraste / Contrast Lighting','Contrast Lighting M.L.',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2327,'acuity holdings','pim','manufacturer','Acuity Holdings','Acuity Brands',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2328,'sanford canada','pim','manufacturer','Sanford Canada',NULL,NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2329,'abb','pim','manufacturer','ABB','ABB',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2330,'ac components orporated','pim','manufacturer','AC Components orporated',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2331,'ace-2 holdings','pim','manufacturer','Ace-2 Holdings',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2332,'gescan generic conduit','pim','manufacturer','GESCAN GENERIC CONDUIT',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2333,'fluke electronics canada','pim','manufacturer','Fluke Electronics Canada','Fluke',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2334,'bob dale gloves','pim','manufacturer','Bob Dale Gloves','Bob Dale Gloves & Imports',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2335,'honeywell','pim','manufacturer','Honeywell','Honeywell',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2336,'beghelli canada','pim','manufacturer','Beghelli Canada','Beghelli',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2337,'dicon global','pim','manufacturer','Dicon Global','Dicon Global',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2338,'mm plastic','pim','manufacturer','MM Plastic','MM Plastics',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2339,'cables pti / pti cables','pim','manufacturer','Cables PTI / PTI Cables','PTI Cables',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2340,'deca cables','pim','manufacturer','Deca Cables','Deca Cables',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2341,'e.c.s. electrical cable supply','pim','manufacturer','E.C.S. Electrical Cable Supply',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2342,'nexans canada','pim','manufacturer','Nexans Canada','Nexans',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2343,'cci thermal technologies','pim','manufacturer','Cci Thermal Technologies','Cci Thermal Technologies',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2344,'calrad electronics','pim','manufacturer','Calrad Electronics','Calrad',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2345,'crc canada','pim','manufacturer','CRC Canada',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2346,'code electric products','pim','manufacturer','Code Electric Products','Code Electric',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2347,'tyco electronics canada','pim','manufacturer','Tyco Electronics Canada','Tyco Electronics',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2348,'british columbia','pim','manufacturer','British Columbia',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2349,'eaton yale company','pim','manufacturer','Eaton Yale Company','Eaton',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2351,'dasal industries','pim','manufacturer','Dasal Industries','Dasal Industries',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2352,'danfoss','pim','manufacturer','Danfoss','DanFoss',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2353,'procter & gamble','pim','manufacturer','Procter & Gamble','Duracell',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2354,'duct-o-wire canada','pim','manufacturer','Duct-O-Wire Canada',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2355,'gescan generic conduit fittings','pim','manufacturer','GESCAN GENERIC CONDUIT FITTINGS',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2356,'excel lighting & mfg','pim','manufacturer','Excel Lighting & mfg','Excel Lighting & Manufacturer',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2357,'fre composites','pim','manufacturer','Fre Composites','FRE Composite',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2358,'national electrical supply','pim','manufacturer','National Electrical Supply',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2360,'federal signal corporation','pim','manufacturer','Federal Signal corporation','Federal Signal',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2361,'hilti (canada) corporation','pim','manufacturer','Hilti (Canada) corporation','Hilti',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2362,'idec canada','pim','manufacturer','Idec Canada','Idec',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2363,'produits standard / standard products','pim','manufacturer','Produits Standard / Standard Products','Standard Products',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2364,'jaftech manufacturing','pim','manufacturer','Jaftech Manufacturing','Jaftech Manufacturing',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2365,'kendal lighting (b.c.)','pim','manufacturer','Kendal Lighting (B.C.)','Kendal Lighting',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2366,'chemco electrical contr.','pim','manufacturer','Chemco Electrical Contr.',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2367,'leviton manufacturing of canada','pim','manufacturer','Leviton Manufacturing of Canada','Leviton',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2368,'primesource building products canada','pim','manufacturer','Primesource Building Products Canada','Lilly Fasteners',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2369,'lind equipment','pim','manufacturer','Lind Equipment','Lind Equipment',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2370,'milwaukee electric tool (canada)','pim','manufacturer','Milwaukee Electric Tool (Canada)','Milwaukee Electric Tools',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2371,'midwest electric products','pim','manufacturer','Midwest Electric Products',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2372,'distri-lite','pim','manufacturer','Distri-Lite',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2373,'marcus transformer of canada','pim','manufacturer','Marcus Transformer Of Canada','Marcus Transformer',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2374,'cooper crouse-hinds','pim','manufacturer','Cooper Crouse-Hinds',NULL,NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2375,'north safety products / produits de sécurité north','pim','manufacturer','North Safety products / Produits De Sécurité North','North Safety Products',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2376,'nuheat industries','pim','manufacturer','Nuheat Industries','Nuheat',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2377,'peerless','pim','manufacturer','Peerless','Peerless Electric',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2378,'pelican products cana','pim','manufacturer','Pelican Products Cana','Pelican',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2379,'panasonic canada','pim','manufacturer','Panasonic Canada','Panasonic',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2380,'progress lighting','pim','manufacturer','Progress Lighting','Progress Lighting',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2381,'puls','pim','manufacturer','Puls','Puls',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2382,'tyco thermal controls (canada)','pim','manufacturer','Tyco Thermal Controls (Canada)',NULL,NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2383,'russell industries','pim','manufacturer','Russell Industries','Russel',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2384,'roxtec','pim','manufacturer','Roxtec','Roxtec',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2385,'ipex inc','pim','manufacturer','Ipex inc',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2386,'sick','pim','manufacturer','Sick','Sick Optics',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2387,'osram sylvania','pim','manufacturer','Osram Sylvania',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2388,'stanpro lighting systems / systèmes d\'Éclairage stanpro','pim','manufacturer','Stanpro Lighting Systems / Systèmes D\'Éclairage Stanpro','Stanpro Lighting Systems',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2389,'stanpro lighting systems / systèmes d\'Éclairage st','pim','manufacturer','Stanpro Lighting Systems / Systèmes D\'Éclairage St','Stanpro Lighting Systems',NULL);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2390,'ushio america','pim','manufacturer','Ushio America',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2391,'universal lighting technologies','pim','manufacturer','Universal Lighting Technologies',NULL,1);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2392,'wera tools','pim','manufacturer','Wera Tools','Wera Tools',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2393,'wieland electric','pim','manufacturer','Wieland Electric','Wieland Electric',0);
INSERT INTO `MappingCode` (`id`,`code`,`source`,`type`,`initialValue`,`value`,`ignored`) VALUES (2394,'emerson electric canada','pim','manufacturer','Emerson Electric Canada','Emerson',NULL);
